# Generated by Django 4.0.3 on 2022-06-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_author_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_id',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', editable=False, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.CharField(default=0, editable=False, max_length=36),
            preserve_default=False,
        ),
    ]
