# Generated by Django 4.0.3 on 2022-06-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_author_id_comment_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_id',
            field=models.CharField(db_index=True, editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.CharField(db_index=True, editable=False, max_length=36),
        ),
    ]
