# Generated by Django 4.0.3 on 2022-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.CharField(choices=[('건물', '건물'), ('학과', '학과'), ('동아리', '동아리')], max_length=30),
        ),
    ]
