# Generated by Django 4.0.3 on 2022-06-02 04:03

from django.db import migrations, models
import spaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='thumbnail',
            field=models.ImageField(default='default_image.jpg', upload_to=spaces.models.get_image_path),
        ),
    ]
