# Generated by Django 4.0.3 on 2022-05-25 21:25

from django.db import migrations
import metaland.models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_options_notice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=metaland.models.TokenUserField(),
        ),
    ]
