# Generated by Django 4.0.3 on 2022-05-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': '네비게이션 링크',
                'verbose_name_plural': '네비게이션 링크',
            },
        ),
    ]
