# Generated by Django 4.0.3 on 2022-05-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navlinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlink',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
